"""Verified stepper/wheel geometry shared by offline analysis tools."""

import math

MOTOR_FULL_STEPS_PER_REV = 200
MICROSTEPS_PER_FULL_STEP = 32
STEPS_PER_REV = MOTOR_FULL_STEPS_PER_REV * MICROSTEPS_PER_FULL_STEP
WHEEL_RADIUS_M = 0.0412
WHEEL_CIRCUMFERENCE_M = 2.0 * math.pi * WHEEL_RADIUS_M
METERS_PER_STEP = WHEEL_CIRCUMFERENCE_M / STEPS_PER_REV
