#!/usr/bin/env bash
set -euo pipefail
TEST=${1:-OFF}

# Configure
if [ "$TEST" = "ON" ]; then 
  BUILD_DIR=build
  CMAKE_ARGS=(
    -DBUILD_TESTS=ON
    -DCMAKE_BUILD_TYPE=Release
  )
else 
  BUILD_DIR=build-pi
  CMAKE_ARGS=(
    -DBUILD_TESTS=OFF
    -DCMAKE_BUILD_TYPE=Release
    -DCMAKE_TOOLCHAIN_FILE="$(realpath cmake/toolchain-rpi4.cmake)"
  )
fi

cmake -S . -B "$BUILD_DIR" "${CMAKE_ARGS[@]}"

# Build
cmake --build "$BUILD_DIR" -j"$(nproc)"

# Run tests
if [ "$TEST" = "ON" ]; then
    ctest --test-dir "$BUILD_DIR" --output-on-failure -j8 --progress
fi
