#!/usr/bin/env python3
from __future__ import annotations

import argparse
import csv
import itertools
import json
import os
import signal
import socket
import subprocess
import sys
import time
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
TEST_PYTHON = REPO_ROOT / "tests" / "python"
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))
if str(TEST_PYTHON) not in sys.path:
    sys.path.insert(0, str(TEST_PYTHON))

from generated_balancer import BalancerMsgId  # noqa: E402
from tests.python.support.simulator_service import (  # noqa: E402
    DONE_COMPLETED,
    PHYSICS_REALISTIC,
    run_scenario_live,
)
from udp_client import UdpClient  # noqa: E402

DEFAULT_SCENARIO = {
    "duration_s": 40.0,
    "velocity_feedback_tau_s": 0.10,
    "com_angle_offset_rad": 0.01,
            "imu_noise_seed": 12345,
            "accel_noise_std_mps2": 0.20,
            "gyro_noise_std_rad_s": 0.015,
    "disturbances": [
        {
            "kind": "hold_bias",
            "start_s": 1.0,
            "duration_s": 0.0,
            "force_n": 0.0,
            "com_bias_rad": 0.02,
        },
    ],
}

PID_KEYS = (
    "rate_P",
    "rate_I",
    "rate_D",
    "rate_I_lim",
    "rate_FF",
    "vel_P",
    "lean_trim_I",
    "lean_trim_max_deg",
    "pitch_P",
    "pitch_D",
)


def _float_list(value: str) -> list[float]:
    return [float(part.strip()) for part in value.split(",") if part.strip()]


def _allocate_udp_port() -> int:
    with socket.socket(socket.AF_INET, socket.SOCK_DGRAM) as sock:
        sock.bind(("127.0.0.1", 0))
        return int(sock.getsockname()[1])


def _read_pid(path: Path) -> dict[str, float]:
    values: dict[str, float] = {}
    for line in path.read_text(encoding="utf-8").splitlines():
        stripped = line.split("#", 1)[0].strip()
        if not stripped or "=" not in stripped:
            continue
        key, raw_value = (part.strip() for part in stripped.split("=", 1))
        if key in PID_KEYS:
            values[key] = float(raw_value)
    missing = [key for key in PID_KEYS if key not in values]
    if missing:
        raise ValueError(f"{path} is missing PID keys: {', '.join(missing)}")
    return values


def _write_pid(path: Path, values: dict[str, float]) -> None:
    lines = [
        "# Balancer Bot PID Configuration",
        "# Generated by tools/sweep_pid.py",
        "",
        "# --- Rate Controller (Inner Loop) ---",
        f"rate_P               = {values['rate_P']:.12g}",
        f"rate_I               = {values['rate_I']:.12g}",
        f"rate_D               = {values['rate_D']:.12g}",
        f"rate_I_lim           = {values['rate_I_lim']:.12g}",
        f"rate_FF              = {values['rate_FF']:.12g}",
        "",
        "# --- Outer Loop ---",
        f"vel_P                = {values['vel_P']:.12g}",
        f"lean_trim_I          = {values['lean_trim_I']:.12g}",
        f"lean_trim_max_deg    = {values['lean_trim_max_deg']:.12g}",
        f"pitch_P              = {values['pitch_P']:.12g}",
        f"pitch_D              = {values['pitch_D']:.12g}",
        "",
    ]
    path.write_text("\n".join(lines), encoding="utf-8")


def _start_simulator(binary: Path, port: int) -> subprocess.Popen:
    proc = subprocess.Popen(
        [str(binary), "--port", str(port)],
        cwd=REPO_ROOT,
        stdout=subprocess.DEVNULL,
        stderr=subprocess.DEVNULL,
        preexec_fn=os.setsid,
    )
    deadline = time.monotonic() + 0.25
    while time.monotonic() < deadline:
        if proc.poll() is not None:
            raise RuntimeError(f"balancer_simulator exited during startup (rc={proc.returncode})")
        time.sleep(0.005)
    return proc


def _stop_process(proc: subprocess.Popen) -> None:
    if proc.poll() is not None:
        return
    os.killpg(os.getpgid(proc.pid), signal.SIGTERM)
    try:
        proc.wait(timeout=5)
    except subprocess.TimeoutExpired:
        os.killpg(os.getpgid(proc.pid), signal.SIGKILL)
        proc.wait(timeout=5)


def _score(summary: dict, done_reason: int) -> float:
  if done_reason != DONE_COMPLETED or summary.get("fell"):
    return 1.0e9
  velocity = abs(float(summary.get("tail_mean_abs_velocity_mps") or 0.0))
  pitch = abs(float(summary.get("tail_mean_abs_pitch_deg") or 0.0))
  rms_pitch = abs(float(summary.get("tail_rms_pitch_deg") or 0.0))
  rails = float(summary.get("tail_rail_fraction") or 0.0)
  command_rails = float(summary.get("tail_command_rail_fraction") or 0.0)
  return 8.0 * velocity + 4.0 * pitch + 8.0 * rms_pitch + 25.0 * (rails + command_rails)


def _candidate_grid(base: dict[str, float], args: argparse.Namespace) -> list[dict[str, float]]:
    axes = {
        "rate_P": _float_list(args.rate_p),
        "rate_I": _float_list(args.rate_i),
        "rate_D": _float_list(args.rate_d),
        "vel_P": _float_list(args.vel_p),
        "lean_trim_I": _float_list(args.lean_trim_i),
        "lean_trim_max_deg": _float_list(args.lean_trim_max_deg),
        "pitch_P": _float_list(args.pitch_p),
        "pitch_D": _float_list(args.pitch_d),
    }
    candidates = []
    for values in itertools.product(*(axes[key] for key in axes)):
        candidate = dict(base)
        candidate.update(dict(zip(axes.keys(), values)))
        candidates.append(candidate)
    return candidates


def _row_for(index: int, pid_path: Path, values: dict[str, float], summary: dict, done_reason: int) -> dict:
    row = {key: values[key] for key in PID_KEYS}
    row.update(
        {
            "rank": 0,
            "index": index,
            "pid_config": str(pid_path),
            "done_reason": done_reason,
            "fell": bool(summary.get("fell")),
            "score": _score(summary, done_reason),
            "final_position_m": summary.get("final_position_m"),
            "max_abs_position_m": summary.get("max_abs_position_m"),
            "tail_mean_abs_velocity_mps": summary.get("tail_mean_abs_velocity_mps"),
            "tail_mean_abs_pitch_deg": summary.get("tail_mean_abs_pitch_deg"),
            "tail_rms_pitch_deg": summary.get("tail_rms_pitch_deg"),
            "max_abs_pitch_deg": summary.get("max_abs_pitch_deg"),
            "max_abs_u_sps": summary.get("max_abs_u_sps"),
            "tail_rail_fraction": summary.get("tail_rail_fraction"),
            "tail_command_rail_fraction": summary.get("tail_command_rail_fraction"),
        }
    )
    return row


def main() -> int:
    parser = argparse.ArgumentParser(description="Sweep simulator PID values and rank hold-bias drift.")
    parser.add_argument("--sim-bin", type=Path, default=REPO_ROOT / "build" / "balancer_simulator")
    parser.add_argument("--base-pid", type=Path, default=REPO_ROOT / "pid_sim.conf")
    parser.add_argument("--output-dir", type=Path, default=REPO_ROOT / "build" / "sim_sweeps" / time.strftime("%Y%m%d_%H%M%S"))
    parser.add_argument("--limit", type=int, default=0, help="Optional cap on candidates, useful for smoke runs.")
    parser.add_argument("--run-id-base", type=int, default=7000)
    parser.add_argument("--rate-p", default="0.10,0.15,0.20,0.25")
    parser.add_argument("--rate-i", default="0.0")
    parser.add_argument("--rate-d", default="0.04,0.08, 0.12, 0.16")
    parser.add_argument("--vel-p", default="0.0003,0.0004, 0.0005, 0.0006, 0.0007")
    parser.add_argument("--lean-trim-i", default="0.30, 0.60")
    parser.add_argument("--lean-trim-max-deg", default="6.0")
    parser.add_argument("--pitch-p", default="4, 6, 8, 10,")
    parser.add_argument("--pitch-d", default="0.0,0.25,0.5")
    args = parser.parse_args()

    if not args.sim_bin.exists():
        raise SystemExit(f"Simulator binary not found at {args.sim_bin}; run pytest --build first.")

    base = _read_pid(args.base_pid)
    candidates = _candidate_grid(base, args)
    if args.limit > 0:
        candidates = candidates[: args.limit]

    args.output_dir.mkdir(parents=True, exist_ok=True)
    pid_dir = args.output_dir / "pid"
    run_dir = args.output_dir / "runs"
    pid_dir.mkdir(parents=True, exist_ok=True)
    run_dir.mkdir(parents=True, exist_ok=True)

    port = _allocate_udp_port()
    proc = _start_simulator(args.sim_bin, port)
    rows: list[dict] = []
    try:
        with UdpClient(bridge_port=port) as udp:
            udp.register()
            udp.drain()
            for index, values in enumerate(candidates):
                pid_path = pid_dir / f"candidate_{index:04d}.conf"
                _write_pid(pid_path, values)
                output_dir = run_dir / f"candidate_{index:04d}"
                summary, _metadata, done = run_scenario_live(
                    udp,
                    run_id=args.run_id_base + index,
                    output_dir=output_dir,
                    physics_profile=PHYSICS_REALISTIC,
                    pid_config_path=str(pid_path),
                    initial_pitch_deg=67.0,
                    done_timeout=15.0,
                    **DEFAULT_SCENARIO,
                )
                row = _row_for(index, pid_path, values, summary, done.reason_code)
                rows.append(row)
                print(
                    f"{index + 1:4d}/{len(candidates)} "
                    f"score={row['score']:.4g} pos={row['final_position_m']:.4g} "
                    f"vel={row['tail_mean_abs_velocity_mps']:.4g} "
                    f"pitch={row['tail_mean_abs_pitch_deg']:.4g}",
                    flush=True,
                )
    finally:
        _stop_process(proc)

    rows.sort(key=lambda row: row["score"])
    for rank, row in enumerate(rows, start=1):
        row["rank"] = rank

    fieldnames = list(rows[0].keys()) if rows else []
    with (args.output_dir / "results.csv").open("w", encoding="utf-8", newline="") as fh:
        writer = csv.DictWriter(fh, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows(rows)
    (args.output_dir / "top10.json").write_text(json.dumps(rows[:10], indent=2), encoding="utf-8")

    print(f"\nWrote {args.output_dir / 'results.csv'}")
    print(json.dumps(rows[: min(5, len(rows))], indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
